# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 100

checkpoint:
  no_epoch_checkpoints: true
  best_checkpoint_metric: wer
  save_interval_updates: 200
  keep_interval_updates: 1
  save_dir : ???

task:
  _name: audio_pretraining
  data: ???
  normalize: false
  labels: ltr
  del_silence: true

dataset:
  num_workers: 6
  max_tokens: 3200000
  skip_invalid_size_inputs_valid_test: true
  validate_after_updates: 10000
  validate_interval: 200
  valid_subset: dev

distributed_training:
  ddp_backend: no_c10d
  distributed_world_size: 4 # number of GPU

criterion:
  _name: ctc
  zero_infinity: true

optimization:
  max_update: 80000
  lr: [0.00003]
  sentence_avg: true
  update_freq: [2]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-08

lr_scheduler:
  _name: tri_stage
  phase_ratio: [0.1, 0.4, 0.5]
  final_lr_scale: 0.05

model:
  _name: wav2vec_ctc # the ASR model which has linear layer on top of wav2vec
  w2v_path: ???
  apply_mask: true
  mask_prob: 0.65
  mask_channel_prob: 0.5
  mask_channel_length: 64
  layerdrop: 0.1
  activation_dropout: 0.1
  feature_grad_mult: 0.0
  freeze_finetune_updates: 10000

